# Generated by Django 4.2.4 on 2023-12-11 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_apellido",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre y Apeliido"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("tema", models.CharField(max_length=200)),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.persona",
                    ),
                ),
            ],
        ),
    ]
