# Generated by Django 4.2.4 on 2023-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="discursos",
            field=models.ManyToManyField(
                related_name="personas", to="register.discurso"
            ),
        ),
    ]
