# Generated by Django 4.2.4 on 2023-12-13 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_persona_discursos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discurso",
            name="cantidad",
        ),
    ]
